source 'https://rubygems.org'
gem 'rails', '4.2.7.1'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'pg'
gem 'devise'

gem 'bootstrap', '~> 4.0.0.alpha5'
gem 'sprockets-rails', :require => 'sprockets/railtie'
gem "rolify"
gem 'carrierwave', '~> 1.0'
gem 'will_paginate'
gem 'will_paginate-bootstrap'
gem 'bootstrap_form'

source 'https://rails-assets.org' do
  gem 'rails-assets-tether', '>= 1.1.0'
end

group :development, :test do
  gem 'byebug'
  gem 'pry'
end

group :development do
  gem 'web-console', '~> 2.0'
end

