# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 148bfc6a6d805d0ce550d7e5925921496d6e2a06121f09b6ed9d95c43bfa56cc5ee6e77fd792b5cc08b9ecff1ae93965b6c2906cda5b844dfe7d02ebde8102bf

test:
  secret_key_base: 4b42d3bdbea461afe6541729841a23865b88ef3761bdbf9439a22a157712458597353da42c71d9180cb342d9e7259df1daea0e5d4c431c5fd13988c66af9eb3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
